import Header from '@/components/header/Header';
import '@/styles/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='antialiased min-h-screen'>
        <Header />

        <div className='m-auto max-w-6xl p-4'>{children}</div>
      </body>
    </html>
  );
}
